name: 'Publish Event To Dynatrace'
description: 'Send build event to dynatrace'
runs:
 using: 'composite'
 steps:
      - name: Inform Dynatrace Build Execution
        uses: dynatrace-oss/dynatrace-github-action@v9
        with:
          url: '${{ env.DT_URL }}'
          token: '${{ env.DT_TOKEN }}'
          events: |
            - title: "Github Build"
              type: CUSTOM_INFO    
              description: "GitHub project ${{ github.repository }} was Executed"
              source: GitHub
              entity-selector: "type(SERVICE),tag(github-build-monitor)"
              properties:
                project: "${{ github.repository }}"
                branch: "${{ github.ref }}"
                event: "${{ github.event_name }}"
                workflow: "${{ github.workflow }}"
                runId: "${{ github.run_id }}"
                actor: "${{ github.actor }}"
                owner: "${{ github.repository_owner }}"
