name: 'Publish To Dynatrace'
description: 'dynatrace to check build metrics'
inputs: 
  artifact-name:
      description: 'artifact name'
      required: true
      type: string 
runs:
 using: 'composite'
 steps:
      - name: Inform Dynatrace about a successful build
        if: ${{ success() }}
        uses: dynatrace-oss/dynatrace-github-action@v9
        with:
          url: '${{ env.DT_URL }}'
          token: '${{ env.DT_TOKEN }}'
          metrics: |
            - metric: "github.build.total"
              value: "1.0"
              dimensions:
                project: "${{ github.repository }}"
                branch: "${{ github.ref }}"
                event: "${{ github.event_name }}"
                owner: BHGitOps
            - metric: "github.build.success"
              value: "1.0"
              dimensions:
                project: "${{ github.repository }}"
                branch: "${{ github.ref }}"
                event: "${{ github.event_name }}"
                owner: BHGitOps
          events: |
            - title: "Successful Build"
              type: CUSTOM_INFO    
              description: "GitHub project ${{ github.repository }} was successfully built"
              source: GitHub
              dimensions:
                project: "${{ github.repository }}"
                branch: "${{ github.ref }}"
                event: "${{ github.event_name }}"
                owner: BHGitOps
      - name: Inform Dynatrace about a failed build 
        if: ${{ failure() }}
        uses: dynatrace-oss/dynatrace-github-action@v9
        with:
          url: '${{ env.DT_URL }}'
          token: '${{ env.DT_TOKEN }}'
          metrics: |
            - metric: "github.build.total"
              value: "1.0"
              dimensions:
                project: "${{ github.repository }}"
                branch: "${{ github.ref }}"
                event: "${{ github.event_name }}"
                owner: BHGitOps
            - metric: "github.build.fails"
              value: "1.0"
              dimensions:
                project: "${{ github.repository }}"
                branch: "${{ github.ref }}"
                event: "${{ github.event_name }}"
                owner: BHGitOps
          events: |
            - title: "Failed build"
              type: CUSTOM_INFO    
              description: "GitHub project ${{ github.repository }} build failed!"
              source: GitHub
              dimensions:
                project: "${{ github.repository }}"
                branch: "${{ github.ref }}"
                event: "${{ github.event_name }}"
                owner: BHGitOps      
